### ISSUE TITLE
Update plot recipe for SimData

### ISSUE THREAD

**Issue by bbejanov** [bankofcanada/StateSpaceEcon.jl#13]
- [ ] print plot_title at the top
- [ ] display single legend for all subplots: could be in an empty subplot (e.g. if grid is (nrow, ncol) and there are fewer than nrox*ncol variables, the empty plot in the bottom right could display only the legend) or could be outside the grid of plots.
- [ ] support optional keyword arguments nrow and ncol. If both are given, that'd be the same as layout = (nrow, ncol). We need the case of only one of them given and the other computed from the number of variables, with some subplots potentially left empty.

**Comment by kunov** [comment]
@bbejanov 

I'll try to tackle this

Procedure:

 - start here: https://github.com/bankofcanada/StateSpaceEcon.jl/blob/master/src/plotrecipes.jl
 - I'll open a pull request
 - then go and attempt steps 1-3

**Comment by bbejanov** [comment]
Category/Catégorie: Non-Sensitive/Non-Délicat


Great, thanks Atai!
====================================================================================

La version française suit le texte anglais.

------------------------------------------------------------------------------------

This email may contain privileged and/or confidential information, and the Bank of
Canada does not waive any related rights. Any distribution, use, or copying of this
email or the information it contains by other than the intended recipient is
unauthorized. If you received this email in error please delete it immediately from
your system and notify the sender promptly by email that you have done so. 

------------------------------------------------------------------------------------

Le présent courriel peut contenir de l'information privilégiée ou confidentielle.
La Banque du Canada ne renonce pas aux droits qui s'y rapportent. Toute diffusion,
utilisation ou copie de ce courriel ou des renseignements qu'il contient par une
personne autre que le ou les destinataires désignés est interdite. Si vous recevez
ce courriel par erreur, veuillez le supprimer immédiatement et envoyer sans délai à
l'expéditeur un message électronique pour l'aviser que vous avez éliminé de votre
ordinateur toute copie du courriel reçu.

**Comment by bbejanov** [comment]
plot recipe moved to TimeSeriesEcon
