### ISSUE TITLE
`dict2array` doesn't support new type assigned to m.varshk

### ISSUE THREAD

**Issue by mariusmjp** [bankofcanada/StateSpaceEcon.jl#17]
Hi

I noticed an issue with dict2array which doesn't support the new type assigned to m.varshk (Array{ModelBaseEcon.ModelSymbol,1}):

![issue with m varshks](https://user-images.githubusercontent.com/22647406/93601518-53cffa80-f98f-11ea-88ca-79c2b04ec59d.png)

**Comment by bbejanov** [comment]
The new `SimData` type is meant for supplying exogenous data and holding the simulation results. Have you tried that, instead of a `Dict`? If `SimData` is missing some feature you need, I'd rather add that feature so you'd use it. `Dict` and `Array` will likely be discontinued for this purpose.

**Comment by mariusmjp** [comment]
No really,

I'm not sure I understand what you want to say. db_f is essentially a collect of several database which are used with fame2series which returns Dict. But I will test and let you know.

**Comment by bbejanov** [comment]
Fix will be available in the upcoming version 0.2
