### ISSUE TITLE
Question: How deal with constant or parameter with SimData object

### ISSUE THREAD

**Issue by mariusmjp** [bankofcanada/StateSpaceEcon.jl#20]
Hi
I tried to test SimData, If I well understand in the future Simulate( ) will be accept uniquely SimData object instead Dict{String,Any} that really interesting for others aspect we can develop in the future like shock decomposition but how you want to deal with parameter or constant which will be used during the simulation and are not tseries ? We need to think at a structure which can store TSeries and constants

**Comment by bbejanov** [comment]
TimeSeriesEcon now has a `Workspace` type which can handle this.
