### ISSUE TITLE
StateSpaceEcon.clear_sstate affected by change brought by ModelBaseEcon v0.3.3

### ISSUE THREAD

**Issue by mariusmjp** [bankofcanada/StateSpaceEcon.jl#24]
Hi 

I suspect StateSpaceEcon.clear_sstate need to be update with change brought by ModelBaseEcon v0.3.3
![StateSpaceEcon clear_sstate_fail](https://user-images.githubusercontent.com/22647406/97059410-5b6e5a80-155e-11eb-90d3-736bd7d9033e.png)

**Comment by bbejanov** [comment]
Will fix in #22
